[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  # Removed exposed API key - use environment variables in production

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
