[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  VITE_GEMINI_API_KEY = "AIzaSyADR8-xyQ4-2WLpGOiVg1_U3qKFfnFan6Y"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
